runtime: python27
api_version: 1
threadsafe: true
service: prueba
#default_expiration: "30d"

handlers:

- url: /
  static_files: dist/index.html

- url: /*
  static_files: dist/index.html
  upload: dist/index.html



skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^\node_modules$
- ^\test$
- ^node_modules$
- ^app$
